site_name: Yeeps Wiki
site_url: https://wiki.yeeps.dev
repo_name: lrutjens/yeeps-wiki
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      tertiary: green
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - navigation.prune
    - navigation.expand
    - navigation.sections
    - navigation.tabs
    - content.code.annotate
    - content.tooltips
    - content.tabs
    - search.suggest
    - search.share
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.blocks.caption
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - toc
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - abbr
  - attr_list
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - search
  - git-committers:
      repository: lrutjens/yeeps-wiki
      branch: master
      enabled: !ENV [CI, false]
  - git-revision-date-localized:
      enable_creation_date: true
      enabled: !ENV [CI, false]
nav:
  - Introduction: index.md
  - Cooking: 
    - Recipe List: cooking/recipeList.md
    - Bacon: cooking/bacon.md
    - Bagel: cooking/bagel.md
    - BLT : cooking/blt.md
    - Baked Potato: cooking/bakedPotato.md
    - Batter: cooking/batter.md
    - Beef: cooking/beef.md
    - Beef Stew: cooking/beefStew.md
    - Bread: cooking/bread.md
    - Breakfast: cooking/breakfast.md
    - Burnt Garbage: cooking/burntGarbage.md
    - Cake: cooking/cake.md
    - Cheese: cooking/cheese.md
    - Cheeseburger: cooking/cheeseburger.md
    - Cheese Sandwich: cooking/cheeseSandwich.md
    - Chicken: cooking/chicken.md
    - Chicken Noodle Soup: cooking/chickenNoodleSoup.md
    - Chicken Parmesan: cooking/chickenParm.md
    - Chicken Tender: cooking/chickenTender.md
    - Cookie: cooking/cookie.md
    - Crepe: cooking/crepe.md
    - Donut: cooking/donut.md
    - Dumpling: cooking/dumpling.md
    - Egg: cooking/egg.md
    - Fancy Mac & Cheese: cooking/fancyMacAndCheese.md
    - Flour: cooking/flour.md
    - French Fries: cooking/frenchFry.md
    - French Toast: cooking/frenchToast.md
    - Fried Chicken: cooking/friedChicken.md
    - Fried Chicken Sandwich: cooking/friedChickenSandwich.md
    - Fried Egg: cooking/friedEgg.md
    - Fried Egg Sandwich: cooking/friedEggSandwich.md
    - Fruit: cooking/fruit.md
    - Fruit Salad: cooking/fruitSalad.md
    - Garbage: cooking/garbage.md
    - Grilled Cheese Sandwich: cooking/grilledCheeseSandwich.md
    - Hamburger: cooking/hamburger.md
    - Hawaiian Pizza: cooking/hawaiianPizza.md
    - Hotdog: cooking/hotdog.md
    - Jelly: cooking/jelly.md
    - Jelly Sandwich: cooking/jellySandwich.md
    - Lasagna: cooking/lasagna.md
    - Lettuce: cooking/lettuce.md
    - Mac & Cheese: cooking/macAndCheese.md
    - Milk: cooking/milk.md
    - Noodles: cooking/noodles.md
    - Pancakes: cooking/pancakes.md
    - Pepperoni Pizza: cooking/pepperoniPizza.md
    - Pie: cooking/pie.md
    - Pizza: cooking/pizza.md
    - Pizza Bagel: cooking/pizzaBagel.md
    - Potato: cooking/potato.md
    - Quesadilla: cooking/quesadilla.md
    - Ramen: cooking/ramen.md
    - Salad: cooking/salad.md
    - Sausage: cooking/sausage.md
    - Spaghetti & Meatballs: cooking/spaghettiAndMeatballs.md
    - Steak: cooking/steak.md
    - Steak Sandwich: cooking/steakSub.md
    - Stir Fry: cooking/stirFry.md
    - Sugar: cooking/sugar.md
    - Syrup: cooking/syrup.md
    - Beef Taco: cooking/tacoBeef.md
    - Chicken Taco: cooking/tacoChicken.md
    - Tomato: cooking/tomato.md
    - Tomato Soup: cooking/tomatoSoup.md
    - Tortilla: cooking/tortilla.md
    - Oven: cooking/oven.md
    - Pot: cooking/pot.md
  - Brewing:
    - Overview: brewing/overview.md
    - Cauldron: brewing/cauldron.md
    - Potion: brewing/potion.md
    - Potions: 
      - Blindness: brewing/blindness.md
      - Giant: brewing/giant.md
      - Haste: brewing/haste.md
      - Healing: brewing/healing.md
      - Hollow: brewing/hollow.md
      - Invisibility: brewing/invisibility.md
      - Levitation: brewing/levitation.md
      - Love: brewing/love.md
      - Neutralizer: brewing/neutralizer.md
      - Night Vision: brewing/nightVision.md
      - Poison: brewing/poison.md
      - Slow Falling: brewing/slowFall.md
      - Slowness: brewing/slowness.md
      - Speed: brewing/speed.md
      - Strength: brewing/strength.md
      - Tiny: brewing/tiny.md
      - Visibility: brewing/visibility.md
      - Weakness: brewing/weakness.md
      - Failed Potion: brewing/failedPotion.md
    - Ingredients:
      - Speed Berries: brewing/berries.md
      - Biggie Bone: brewing/bone.md
      - Magic Brewshroom: brewing/brewshroom.md
      - Tall Magic Brewshroom: brewing/tallBrewshroom.md
      - Spooky Eyeball: brewing/eyeball.md
      - Goodie Flower: brewing/flowerYellow.md
      - Corrupted Flower: brewing/flowerPurple.md
      - Floaty Feather: brewing/feather.md
      - Healthy Leaf: brewing/leaf.md
      - Tail: brewing/tail.md
      - Buff Tentacle: brewing/tentacle.md

extra:
  mermaid:
    theme: default
    flowchart:
      htmlLabels: true
  consent:
    title: Cookie consent
    description: We use cookies to recognize your repeated visits and preferences, as well as to measure the effectiveness of our documentation and whether users find what they're searching for. With your consent, you're helping us tomake our documentation better.
  analytics:
    provider: google
    property: G-EW22YE9GT6
  generator: false
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/P9nqvfTrQB
      name: Yeeps Wiki Team
extra_css:
  - stylesheets/extra.css